# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51ebf3a938f0055a486df4e20338997b6b92245a5bc13ecc9b357a47bb821d3e0359a9395c10b157e50b58e2c7a92ef96810a3607123855b2fbad97526964ef3

test:
  secret_key_base: 129742c313d4168a5e6c0ae37c07e0140212c49c48787637b92dd489d6fa25bbecb867df3e9df9533d8f6defdab5b00dc0b4d49e023b376732f478c31cb96855

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
